apiVersion: apps/v1
kind: Deployment
metadata:
  name: anbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anbuggy
  template:
    metadata:
      labels:
        app: anbuggy
    spec:
      containers:
      - name: anbuggy
        image: 819177268001.dkr.ecr.us-west-2.amazonaws.com/asmaanouha
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: anbuggy
    k8s-app: anbuggy
  name: anbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: anbuggy
